package tabu;

public class EngData {

    public static final int TOPLAM = 318;

    private static String[][] k0() {
        return new String[][] {
            {"Backpack","travel","carry","bag","shoulder","trip"},
            {"Suitcase","luggage","travel","clothes","airport","carry"},
            {"Passport","identity","country","travel","border","document"},
            {"Ticket","travel","seat","entry","paper","transport"},
            {"Airport","plane","terminal","flight","travel","security"},
            {"Flight","plane","travel","air","journey","passenger"},
            {"Hotel","room","stay","travel","bed","service"},
            {"Reservation","booking","date","hotel","confirm","plan"},
            {"Beach","sand","sea","sun","vacation","relax"},
            {"Sunset","evening","sky","orange","horizon","sun"},
            {"Island","sea","land","tropical","remote","beach"},
            {"Forest","trees","nature","green","animals","wild"},
            {"Mountain","high","climb","rock","peak","nature"},
            {"River","water","flow","long","nature","stream"},
            {"Desert","sand","hot","dry","sun","empty"},
            {"Storm","rain","wind","thunder","lightning","weather"},
            {"Lightning","flash","sky","storm","electricity","light"},
            {"Thunder","sound","storm","loud","sky","lightning"},
            {"Rainbow","colors","sky","rain","arc","light"},
            {"Cloud","sky","white","rain","float","air"},
            {"Laptop","computer","portable","screen","keyboard","battery"},
            {"Keyboard","keys","typing","input","letters","computer"},
            {"Mouse","click","pointer","move","computer","device"},
            {"Screen","display","monitor","pixels","light","image"},
            {"Battery","power","energy","charge","device","electricity"},
            {"Charger","cable","power","plug","device","energy"},
            {"Headphones","audio","music","ears","sound","listen"},
            {"Speaker","sound","loud","music","device","audio"},
            {"Camera","photo","lens","capture","image","record"},
            {"Video","motion","recording","screen","media","play"},
            {"Game","play","fun","level","score","control"},
            {"Level","progress","stage","game","difficulty","advance"},
            {"Player","user","control","game","character","person"},
            {"Enemy","opponent","fight","game","attack","rival"},
            {"Victory","win","success","game","achievement","result"},
            {"Defeat","lose","fail","game","result","end"},
            {"Score","points","game","result","number","record"},
            {"Leaderboard","ranking","score","list","top","players"},
            {"Controller","buttons","input","game","device","control"},
            {"Console","gaming","device","screen","controller","play"},
            {"Friend","person","close","trust","talk","social"},
            {"Conversation","talk","chat","speak","discuss","words"},
            {"Message","text","send","phone","communication","reply"},
            {"Call","phone","speak","voice","connect","talk"},
            {"Reply","answer","message","respond","text","communication"},
            {"Silence","quiet","no sound","calm","still","mute"},
            {"Argument","fight","disagreement","talk","conflict","words"},
            {"Apology","sorry","mistake","forgive","regret","admit"},
            {"Trust","belief","rely","confidence","relationship","safe"},
            {"Respect","value","treat","honor","person","behavior"},
            {"School","education","class","student","teacher","learn"},
            {"Teacher","educate","class","explain","lesson","student"},
            {"Student","learn","school","study","class","exam"},
            {"Exam","test","questions","score","school","result"},
            {"Homework","task","study","school","assignment","work"},
            {"Notebook","write","pages","notes","school","paper"},
            {"Pen","write","ink","paper","tool","draw"},
            {"Board","write","chalk","class","teacher","lesson"},
            {"Lesson","subject","learn","class","topic","school"},
            {"Break","rest","time","pause","school","relax"},
            {"Doctor","hospital","patient","treat","medicine","health"},
            {"Nurse","assist","patient","care","hospital","help"},
            {"Medicine","drug","treat","health","cure","pill"},
            {"Pain","hurt","body","injury","feeling","ache"},
            {"Health","body","fitness","condition","care","life"},
            {"Exercise","fitness","movement","body","workout","health"},
            {"Running","fast","legs","move","sport","speed"},
            {"Swimming","water","pool","move","sport","breathe"},
            {"Breathing","air","lungs","inhale","exhale","life"},
            {"Heart","blood","beat","body","organ","life"},
            {"Robot","machine","move","automatic","technology","task"},
            {"AI","intelligence","learning","data","system","smart"},
            {"Code","program","write","logic","software","computer"},
            {"Bug","error","code","problem","fix","issue"},
            {"Fix","repair","solve","problem","correct","improve"},
            {"Update","new","version","improve","system","install"},
            {"Download","file","internet","save","data","transfer"},
            {"Upload","send","file","internet","data","transfer"},
            {"Network","connect","system","internet","communication","link"},
            {"Art","create","draw","paint","express","design"},
            {"Painting","colors","brush","canvas","art","image"},
            {"Music","sound","rhythm","melody","listen","song"},
            {"Song","music","lyrics","sing","audio","track"},
            {"Dance","move","rhythm","body","music","motion"},
            {"Movie","film","watch","screen","actor","story"},
            {"Actor","perform","role","film","character","scene"},
            {"Director","lead","film","scene","camera","production"},
            {"Script","write","story","dialogue","film","plan"},
            {"Scene","part","film","moment","camera","action"},
            {"Wallet","money","cards","pocket","leather","carry"},
            {"Keychain","keys","ring","small","metal","holder"},
            {"Lock","secure","key","door","safety","close"},
            {"Handle","door","hold","grip","open","metal"},
            {"Stairs","steps","up","down","building","climb"},
            {"Elevator","lift","floor","button","building","up"},
            {"Button","press","control","device","switch","click"},
            {"Remote","control","TV","buttons","signal","device"},
            {"Cable","wire","connect","power","plug","line"},
            {"Plug","socket","power","electricity","insert","cable"},
            {"Fan","air","cool","spin","summer","device"},
            {"Heater","warm","winter","heat","room","device"},
            {"Lamp","light","bulb","desk","bright","room"},
            {"Curtain","window","cover","fabric","light","close"},
            {"Carpet","floor","soft","room","fabric","walk"},
            {"Sofa","sit","living room","comfort","cushion","relax"},
            {"Chair","sit","legs","wood","furniture","table"},
            {"Table","surface","eat","work","furniture","flat"},
            {"Shelf","hold","books","wall","storage","items"},
            {"Drawer","pull","store","cabinet","slide","items"},
            {"Shirt","wear","clothes","fabric","top","button"},
            {"Jacket","coat","warm","outer","wear","winter"},
            {"Shoes","feet","walk","wear","pair","sole"},
            {"Socks","feet","pair","wear","soft","cotton"},
            {"Hat","head","wear","sun","style","cap"},
            {"Glasses","vision","lenses","wear","eyes","frame"},
            {"Watch","time","wrist","clock","wear","seconds"},
            {"Ring","finger","jewelry","gold","wear","circle"},
            {"Necklace","chain","neck","jewelry","wear","pendant"},
            {"Bracelet","wrist","jewelry","band","wear","style"},
            {"Breakfast","morning","eat","meal","start","food"},
            {"Lunch","midday","meal","eat","break","food"},
            {"Dinner","evening","meal","eat","night","food"},
            {"Snack","small","eat","quick","food","bite"},
            {"Bread","bake","slice","wheat","food","loaf"},
            {"Cheese","dairy","slice","milk","food","yellow"},
            {"Egg","shell","breakfast","cook","food","white"},
            {"Rice","grain","cook","bowl","food","white"},
            {"Soup","hot","liquid","bowl","spoon","meal"},
            {"Salad","vegetables","fresh","bowl","healthy","food"},
            {"Sugar","sweet","white","taste","food","crystals"},
            {"Salt","white","taste","food","sprinkle","sodium"},
            {"Pepper","spice","black","taste","food","grind"},
            {"Oil","liquid","cook","pan","food","fry"},
            {"Butter","dairy","spread","melt","bread","fat"},
            {"Knife","cut","sharp","blade","kitchen","tool"},
            {"Fork","prongs","eat","utensil","food","metal"},
            {"Spoon","scoop","soup","utensil","food","bowl"},
            {"Plate","dish","serve","food","round","table"},
            {"Cup","drink","liquid","handle","mug","beverage"},
            {"Coffee","drink","caffeine","cup","hot","energy"},
            {"Tea","drink","leaves","hot","cup","calm"},
            {"Juice","fruit","drink","liquid","sweet","glass"},
            {"Water","drink","clear","liquid","life","thirst"},
            {"Milk","dairy","white","drink","cow","glass"},
            {"Soda","fizzy","drink","bubbles","sweet","can"},
            {"Ice","cold","frozen","water","cube","chill"},
            {"Fridge","cold","store","food","kitchen","cool"},
            {"Freezer","freeze","cold","ice","food","storage"},
            {"Oven","bake","heat","kitchen","cook","food"},
            {"Bus","transport","city","passengers","stop","route"},
            {"Train","rail","travel","station","carriage","track"},
            {"Taxi","ride","fare","city","driver","car"},
            {"Bike","pedal","ride","wheels","street","balance"},
            {"Helmet","safety","head","wear","protect","ride"},
            {"Map","directions","location","route","guide","find"},
            {"Compass","north","direction","needle","navigate","travel"},
            {"Ticket booth","buy","entry","window","pay","line"},
            {"Turnstile","gate","entry","card","pass","station"},
            {"Platform","train","wait","station","edge","board"},
            {"Library","books","quiet","read","borrow","study"},
            {"Classroom","desks","teacher","students","lesson","school"},
            {"Projector","screen","light","presentation","image","class"},
            {"Whiteboard","write","marker","erase","class","teach"},
            {"Marker","ink","write","board","draw","pen"},
            {"Chalk","dust","write","board","class","white"},
            {"Backpack strap","shoulder","carry","bag","adjust","hold"},
            {"Locker","storage","school","lock","metal","door"},
            {"Hallway","corridor","school","walk","doors","long"},
            {"Bell","ring","class","time","school","sound"},
            {"Gym","workout","fitness","weights","exercise","room"},
            {"Treadmill","run","belt","gym","speed","machine"},
            {"Dumbbell","weight","lift","arm","gym","metal"},
            {"Barbell","weight","lift","bar","gym","strength"},
            {"Mat","floor","yoga","exercise","soft","stretch"},
            {"Stretch","muscles","extend","warmup","body","move"},
            {"Coach","train","guide","team","advice","sports"},
            {"Team","group","players","together","match","sport"},
            {"Referee","rules","whistle","judge","game","decision"},
            {"Stadium","seats","crowd","field","game","arena"},
            {"Camera lens","focus","glass","zoom","photo","optics"},
            {"Tripod","stand","stable","camera","legs","support"},
            {"Microphone stand","hold","mic","stage","adjust","pole"},
            {"Mixer","audio","levels","control","sound","board"},
            {"Headset mic","voice","gaming","talk","boom","audio"},
            {"Stream overlay","graphics","live","screen","layout","broadcast"},
            {"Chat window","messages","live","text","viewers","stream"},
            {"Clip highlight","short","video","best","share","moment"},
            {"Thumbnail","image","preview","video","small","cover"},
            {"Upload queue","pending","files","send","list","process"},
            {"Planner","schedule","dates","tasks","organize","book"},
            {"Checklist","tasks","tick","complete","list","items"},
            {"Deadline","due","time","finish","date","pressure"},
            {"Reminder","alert","time","notify","task","app"},
            {"Focus mode","block","distractions","work","concentrate","setting"},
            {"Break timer","rest","interval","time","pause","work"},
            {"Productivity","output","efficiency","work","results","focus"},
            {"Workflow","steps","process","tasks","sequence","system"},
            {"Milestone","goal","stage","project","progress","mark"},
            {"Review","check","evaluate","feedback","improve","assess"},
            {"Backyard","house","grass","fence","outside","garden"},
            {"Fence","wood","border","yard","barrier","gate"},
            {"Gate","entrance","open","close","fence","metal"},
            {"Mailbox","letters","post","mail","box","street"},
            {"Envelope","paper","letter","seal","send","address"},
            {"Stamp","mail","sticker","post","letter","cost"},
            {"Package","box","delivery","shipping","item","send"},
            {"Courier","deliver","package","service","transport","fast"},
            {"Receipt","paper","proof","purchase","store","payment"},
            {"Cashier","register","money","store","pay","counter"},
            {"Mirror","reflection","glass","face","look","image"},
            {"Toothbrush","teeth","clean","bathroom","brush","hygiene"},
            {"Toothpaste","mint","teeth","squeeze","clean","tube"},
            {"Towel","dry","water","bathroom","cloth","shower"},
            {"Soap","clean","wash","foam","hands","hygiene"},
            {"Shampoo","hair","wash","bottle","clean","shower"},
            {"Comb","hair","brush","style","teeth","straighten"},
            {"Hairdryer","blow","hot","hair","dry","device"},
            {"Sink","water","wash","faucet","bathroom","basin"},
            {"Faucet","water","turn","sink","tap","flow"},
            {"Garage","car","park","house","door","storage"},
            {"Driveway","car","path","house","park","entrance"},
            {"Sidewalk","walk","street","pavement","path","city"},
            {"Crosswalk","street","lines","walk","safe","crossing"},
            {"Traffic light","red","green","yellow","stop","go"},
            {"Speed limit","sign","road","number","drive","rule"},
            {"Parking meter","coin","time","street","pay","car"},
            {"Ticket fine","penalty","parking","rule","pay","violation"},
            {"License","drive","permit","car","legal","ID"},
            {"Insurance","policy","safety","car","coverage","pay"},
            {"Factory","production","machines","workers","industry","build"},
            {"Warehouse","storage","boxes","large","goods","inventory"},
            {"Forklift","lift","pallets","warehouse","machine","move"},
            {"Assembly line","production","process","factory","steps","build"},
            {"Blueprint","design","plan","building","drawing","architecture"},
            {"Contract","agreement","sign","legal","terms","deal"},
            {"Invoice","bill","payment","business","amount","due"},
            {"Salary","pay","monthly","job","income","money"},
            {"Bonus","extra","reward","pay","job","incentive"},
            {"Promotion","higher","job","role","advance","career"},
            {"Startup","new","company","business","idea","launch"},
            {"Pitch","present","idea","investors","talk","startup"},
            {"Investor","money","fund","business","capital","return"},
            {"Equity","ownership","shares","company","stake","value"},
            {"Revenue","income","sales","business","money","earnings"},
            {"Profit","gain","money","revenue","business","result"},
            {"Loss","negative","money","deficit","business","result"},
            {"Budget","plan","money","limit","spend","finance"},
            {"Expense","cost","spend","money","business","item"},
            {"Savings","money","store","future","bank","reserve"},
            {"Bank","money","account","deposit","withdraw","finance"},
            {"ATM","cash","machine","card","withdraw","bank"},
            {"Credit card","pay","swipe","limit","bill","plastic"},
            {"Debit card","pay","bank","account","money","swipe"},
            {"Loan","borrow","bank","interest","repay","money"},
            {"Interest","rate","money","loan","extra","percent"},
            {"Mortgage","house","loan","bank","property","payment"},
            {"Rent","pay","monthly","apartment","live","lease"},
            {"Utility bill","electricity","water","gas","pay","home"},
            {"Subscription","monthly","service","pay","renew","plan"},
            {"Garden","plants","flowers","soil","water","grow"},
            {"Shovel","dig","soil","garden","tool","ground"},
            {"Rake","leaves","gather","yard","tool","clean"},
            {"Lawnmower","grass","cut","yard","machine","lawn"},
            {"Hose","water","spray","garden","pipe","flexible"},
            {"Sprinkler","water","lawn","rotate","spray","garden"},
            {"Seeds","plant","grow","soil","small","start"},
            {"Fertilizer","nutrients","soil","plant","grow","garden"},
            {"Weeds","unwanted","plants","remove","garden","wild"},
            {"Compost","organic","waste","soil","recycle","garden"},
            {"Bakery","bread","cakes","oven","shop","bake"},
            {"Pastry","sweet","bakery","dough","dessert","treat"},
            {"Croissant","flaky","butter","pastry","French","breakfast"},
            {"Donut","sweet","fried","ring","glaze","dessert"},
            {"Cupcake","small","cake","frosting","dessert","sweet"},
            {"Pancake","flat","breakfast","syrup","pan","batter"},
            {"Waffle","grid","breakfast","syrup","iron","crisp"},
            {"Syrup","sweet","pour","pancake","sticky","liquid"},
            {"Grill","cook","meat","fire","outdoor","barbecue"},
            {"Barbecue","grill","meat","smoke","outdoor","cook"},
            {"Picnic","outdoor","food","blanket","park","relax"},
            {"Blanket","soft","cover","fabric","warm","ground"},
            {"Cooler","cold","drinks","ice","box","keep"},
            {"Thermos","hot","drink","keep","insulated","bottle"},
            {"Napkin","wipe","table","paper","clean","meal"},
            {"Trash bag","garbage","waste","plastic","throw","bin"},
            {"Recycling bin","paper","plastic","sort","waste","green"},
            {"Compost bin","organic","waste","garden","recycle","soil"},
            {"Broom","sweep","floor","clean","handle","bristles"},
            {"Dustpan","collect","dirt","sweep","floor","tray"},
            {"Laundry","wash","clothes","machine","detergent","clean"},
            {"Detergent","soap","wash","clothes","powder","liquid"},
            {"Washer","machine","clothes","spin","clean","water"},
            {"Dryer","machine","heat","clothes","dry","tumble"},
            {"Clothesline","hang","dry","outside","rope","clips"},
            {"Iron","press","clothes","heat","wrinkles","smooth"},
            {"Ironing board","flat","clothes","iron","surface","fold"},
            {"Stain","mark","clothes","remove","dirty","spot"},
            {"Bleach","whiten","clean","strong","chemical","clothes"},
            {"Fabric softener","scent","clothes","soft","wash","liquid"},
            {"Pet","animal","home","care","companion","owner"},
            {"Dog leash","walk","control","pet","strap","collar"},
            {"Cat litter","box","sand","waste","clean","pet"},
            {"Aquarium filter","water","clean","fish","tank","device"},
            {"Pet food","eat","animal","bowl","feed","kibble"},
            {"Veterinarian","doctor","animal","health","clinic","care"},
            {"Vaccination","shot","health","protect","disease","immune"},
            {"Collar tag","name","pet","ID","attach","safety"},
            {"Pet carrier","transport","cage","travel","animal","box"},
            {"Grooming","clean","brush","pet","fur","care"},
            {"Festival","event","crowd","music","celebrate","day"},
            {"Parade","street","march","floats","crowd","show"},
            {"Fireworks","sky","explode","light","celebration","night"},
            {"Carnival","rides","games","fun","fair","colorful"},
            {"Ride queue","wait","line","turn","theme","park"},
            {"Roller coaster","track","fast","drop","thrill","ride"},
            {"Ferris wheel","circle","cabins","high","view","ride"},
            {"Game booth","win","prize","toss","ring","stall"},
            {"Prize","reward","win","game","gift","award"}
        };
    }

    public static String ana(int i) {
        if (i < 318) { String[][] a = k0(); return a[i-0][0]; }
        return "";
    }

    public static String yasak(int i, int j) {
        if (i < 318) { String[][] a = k0(); return a[i-0][j+1]; }
        return "";
    }
}
